# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.4/metricbeat-module-kibana.html

- module: kibana
  xpack.enabled: true
  metricsets:
    - cluster_actions
    - cluster_rules
    - node_actions
    - node_rules
    - settings
    - stats
    - status
  period: 10s
  hosts: ["https://my-deployment-158070.kb.us-west-1.aws.found.io:9243"]
  #basepath: ""
  username: ${METRICBEAT_SETUP_USERNAME}
  password: ${METRICBEAT_SETUP_PASSWORD}